// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_data from "./routes/api/data.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $index_lemon from "./routes/index_lemon.tsx";
import * as $sse_client from "./routes/sse-client.js";
import * as $Counter from "./islands/Counter.tsx";
import * as $DataIsland from "./islands/DataIsland.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/data.ts": $api_data,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/index_lemon.tsx": $index_lemon,
    "./routes/sse-client.js": $sse_client,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/DataIsland.tsx": $DataIsland,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
